site_name: Pandunia
site_url: http://www.pandunia.info/espani
repo_url: https://github.com/barumau/pandunia/
docs_dir: ../../espani
site_dir: ../../html/espani
theme:
  name: cerulean
  language: es
plugins:
    - search:
        lang: es
nav:
    - Inicio: 'index.md'
    - 'Info':
        - 'Principios': filsofe.md
    - 'Lessons':
        - 'Ortografía': abc.md
        - 'Frases básicas': fraze.md
        - 'Curso': darse.md
    - 'Diccionarios':
        - 'Pandunia-Español': pandunia-espani.md
        - 'Español-Pandunia': espani-pandunia.md
        - 'Diccionario etimologico': leksaslia.md

