site_name: пандуния
site_url: http://www.pandunia.info/rusi
repo_url: https://github.com/barumau/pandunia/
docs_dir: ../../rusi
site_dir: ../../html/rusi
theme: 
  name: cerulean
  language: ru
plugins:
    - search:
        lang: ru
nav:
    - Дом: 'index.md'
    - 'Звучание': abc.md
    - 'Уроки': darse.md
    - 'Словарь':
        - 'пандуния-русский': pandunia-rusi.md
        - 'русский-пандуния': rusi-pandunia.md
        - 'этимология': leksaslia.md
    - 'Грамматика': kanun.md

